# Generated by Django 3.0 on 2021-07-04 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 7, 4, 7, 2, 44, 788252))),
            ],
        ),
    ]
